version: '3.5'
services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - 8000:8080
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - 8001:80
  cassandra:
    image: cassandra:3.11.2
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
    restart: always
    healthcheck:
      test: ["CMD", "cqlsh", "-u cassandra", "-p cassandra" ,"-e describe keyspaces"]
      interval: 15s
      timeout: 10s
      retries: 10